### ISSUE TITLE
Error: Processing the pdf failed due to excess load. Please try again later. Check the URL if there is https:// at the beginning. If not, add it.

### ISSUE THREAD

**Issue by xiongzhenglong** [Ulov888/chatpdflike#4]
我这里pdf 都报错，希望能帮忙看看
[量化.pdf](https://github.com/Ulov888/chatpdflike/files/11056468/default.pdf)

**Comment by Ulov888** [comment]
你是选择直接输入pdf的url还是本地upload？建议两种方式都试一下

**Comment by Ethiopia26** [comment]
Error: Processing the pdf failed due to excess load. Please try again later. Check the URL if there is https:// at the beginning. If not, add it.

**Comment by Ethiopia26** [comment]
raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x12562e490 state=finished raised AuthenticationError>]

**Comment by Ulov888** [comment]
请贴上完整的报错信息

> raise retry_exc from fut.exception() tenacity.RetryError: RetryError[<Future at 0x12562e490 state=finished raised AuthenticationError>]

**Comment by wccccp** [comment]
Serving Flask app 'run'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.1.88:8080
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 455-077-019
192.168.1.10 - - [29/Mar/2023 08:46:19] "GET / HTTP/1.1" 200 -
192.168.1.10 - - [29/Mar/2023 08:46:19] "GET /static/js/script.js HTTP/1.1" 304 -
192.168.1.10 - - [29/Mar/2023 08:46:19] "GET /static/css/styles.css HTTP/1.1" 304 -
192.168.1.10 - - [29/Mar/2023 08:46:19] "GET /static/send-icon.png HTTP/1.1" 304 -
Processing pdf
192.168.1.10 - - [29/Mar/2023 08:46:26] "POST /process_pdf HTTP/1.1" 500 -
INFO:werkzeug:192.168.1.10 - - [29/Mar/2023 08:46:26] "POST /process_pdf HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/mnt1/wcp/chatpdf/chatpdflike/run.py", line 24, in process_pdf
    df = chatbot.paper_df(paper_text)
  File "/mnt1/wcp/chatpdf/chatpdflike/generate_embedding.py", line 75, in paper_df
    df['length'] = df['text'].apply(lambda x: len(x))
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/appuser/miniconda3/envs/wcpchatpdf/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'text'

**Comment by zhangnn520** [comment]
我也是怎么错误，index.html中有些图片路径改后正常了，但是还是存在Error: Processing the pdf failed due to excess load. Please try again later. Check the URL if there is https:// at the beginning. If not, add it.
